[server]
; s=127.0.0.1:9901
; x=127.0.0.1:9902
; r=127.0.0.1:80
; k=KEY_OF_SERVER
; T=CTRL_KEY_OF_SERVER
; v=0
; L=./trp-server.log

[client]
; s=127.0.0.1:9901
; r=127.0.0.1:80
; d=DEVID_OF_CLIENT
; k=KEY_OF_SERVER
; K=KEY_OF_CLIENT
; c=1
; v=0
; L=./trp-client.log

[socks@cli]
; x=127.0.0.1:9902
; b=127.0.0.1:8801
; d=DEVID_OF_CLIENT
; k=KEY_OF_SERVER
; K=KEY_OF_CLIENT
; u=1
; v=0
; L=./trp-socks.log

[tunnel@cli]
; x=127.0.0.1:9902
; b=127.0.0.1:8802
; t=127.0.0.1:22
; d=DEVID_OF_CLIENT
; k=KEY_OF_SERVER
; K=KEY_OF_CLIENT
; u=1
; v=0
; L=./trp-tunnel.log

[shell@srv]
; x=127.0.0.1:9902
; T=CTRL_KEY_OF_SERVER
; k=KEY_OF_SERVER

[shell@cli]
; x=127.0.0.1:9902
; T=CTRL_KEY_OF_CLIENT
; d=DEVID_OF_CLIENT
; k=KEY_OF_SERVER
; K=KEY_OF_CLIENT
