name: package

on:
  workflow_dispatch:
    inputs:
      libuv_version:
        description: "Libuv version"
        required: true
        type: string
        default: "1.52.1"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Download libuv source code
      run: |
        wget "https://dist.libuv.org/dist/v${{ inputs.libuv_version }}/libuv-v${{ inputs.libuv_version }}.tar.gz"
        tar xf "libuv-v${{ inputs.libuv_version }}.tar.gz"
    - name: Configure and build
      run: |
        docker run --rm -v $PWD:/src -w /src ubuntu:18.04 bash -c '\
          set -e; \
          apt update; \
          apt install -y cmake git; \
          mkdir build; \
          cd build; \
          cmake .. -DLIBUV_SRC_PATH="../libuv-v${{ inputs.libuv_version }}" \
            -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install; \
          make install; \
        '
        sudo chown -R $USER: install
    - name: Package
      working-directory: install/bin
      run: |
        commitid=$(git rev-parse --short HEAD)
        strip trp-*
        cp ../../trp.ini .
        zip ../trp-${commitid}-linux-x86_64.zip *
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: trp-linux-x86_64
        path: install/trp-*.zip
        archive: false
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
    - name: Download libuv source code
      run: |
        Invoke-WebRequest -Uri "https://dist.libuv.org/dist/v${{ inputs.libuv_version }}/libuv-v${{ inputs.libuv_version }}.tar.gz" -OutFile "libuv-v${{ inputs.libuv_version }}.tar.gz"
        tar xf libuv-v${{ inputs.libuv_version }}.tar.gz
    - name: Configure and build
      run: |
        cmake -B build -S . -DLIBUV_SRC_PATH="libuv-v${{ inputs.libuv_version }}" -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>"
        cmake --build build --config Release
        cmake --install build --prefix install
    - name: Package
      working-directory: install/bin
      run: |
        $CommitId = git rev-parse --short HEAD
        Copy-Item ../../trp.ini -Destination .
        Compress-Archive -Path * -DestinationPath ../trp-$CommitId-windows-x86_64.zip
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: trp-windows-x86_64
        path: install/trp-*.zip
        archive: false
